/* eslint-disable global-require */
/* eslint-disable @typescript-eslint/no-var-requires */
import { ImageSourcePropType } from 'react-native'

export const deliveryFee = 7.0

export const products = [
  {
    id: '1',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    image: require('../assets/coffees/expresso.png') as ImageSourcePropType,
    tags: ['tradicional'],
    price: 7.9,
  },
  {
    id: '2',
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    image: require('../assets/coffees/americano.png') as ImageSourcePropType,
    tags: ['tradicional'],
    price: 8.9,
  },
  {
    id: '3',
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    image: require('../assets/coffees/expresso-cremoso.png') as ImageSourcePropType,
    tags: ['tradicional'],
    price: 8.9,
  },
  {
    id: '4',
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    image: require('../assets/coffees/cafe-gelado.png') as ImageSourcePropType,
    tags: ['tradicional'],
    price: 8.9,
  },
  {
    id: '5',
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    image: require('../assets/coffees/cafe-com-leite.png') as ImageSourcePropType,
    tags: ['tradicional'],
    price: 8.9,
  },
  {
    id: '6',
    name: 'Latte',
    description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    image: require('../assets/coffees/latte.png') as ImageSourcePropType,
    tags: ['tradicional'],
    price: 9.9,
  },
  {
    id: '7',
    name: 'Capuccino',
    description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    image: require('../assets/coffees/capuccino.png') as ImageSourcePropType,
    tags: ['doce'],
    price: 9.9,
  },
  {
    id: '8',
    name: 'Macchiato',
    description: 'Café expresso misturado com um pouco de leite quente e espuma',
    image: require('../assets/coffees/macchiato.png') as ImageSourcePropType,
    tags: ['tradicional'],
    price: 10.9,
  },
  {
    id: '9',
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    image: require('../assets/coffees/mochaccino.png') as ImageSourcePropType,
    tags: ['doce'],
    price: 10.9,
  },
  {
    id: '10',
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    image: require('../assets/coffees/chocolate-quente.png') as ImageSourcePropType,
    tags: ['doce'],
    price: 11.9,
  },
  {
    id: '11',
    name: 'Cubano',
    description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    image: require('../assets/coffees/cubano.png') as ImageSourcePropType,
    tags: ['especial', 'alcoólico'],
    price: 13.9,
  },
  {
    id: '12',
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    image: require('../assets/coffees/havaiano.png') as ImageSourcePropType,
    tags: ['especial'],
    price: 12.9,
  },
  {
    id: '13',
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    image: require('../assets/coffees/arabe.png') as ImageSourcePropType,
    tags: ['especial'],
    price: 13.9,
  },
  {
    id: '14',
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    image: require('../assets/coffees/irlandes.png') as ImageSourcePropType,
    tags: ['especial', 'alcoólico'],
    price: 14.9,
  },
]
